import {execFileSync} from 'node:child_process';
import {readFileSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {caseDigest,observationDigest} from './fixture-hash.mjs';
const pi=resolve(process.argv[2]),lock=JSON.parse(readFileSync('parity/baseline/upstream.lock.json'));
if(execFileSync('git',['-C',pi,'rev-parse','HEAD'],{encoding:'utf8'}).trim()!==lock.upstream.commit)throw Error('baseline mismatch');
if(execFileSync('git',['-C',pi,'status','--porcelain','--untracked-files=no'],{encoding:'utf8'}).trim())throw Error('dirty baseline');
const outcome=JSON.parse(execFileSync('python3',['parity/terminal/maintenance.py',pi],{encoding:'utf8'}));
const c={schema_version:'1.0.0',id:'cli/interactive/maintenance-cli',catalog_id:'contract:codingagent/interactive-maintenance',surface:'cli',input:{steps:['session stats','compact with instructions and continued context','reload templates skills and context','HTML export and failure','compaction failure and cancellation','continue and exit'],terminal:{rows:40,columns:120}},observe:['outcome','side_effects']};
const observation={outcome,side_effects:[]};
const fixture={schema_version:'1.0.0',deterministic:true,baseline_id:lock.baseline_id,baseline_commit:lock.upstream.commit,upstream:{repository:lock.upstream.repository,commit:lock.upstream.commit,reference:'packages/coding-agent/src/modes/interactive/interactive-mode.ts'},case:c,observation,input_hash:caseDigest(c),observation_hash:observationDigest(observation),execution_method:'node parity/oracle/maintenance-cli.mjs <locked-pi-checkout>',platform:'posix',environment:{terminal:'xterm-256color',transport:'real child process + PTY; offline controlled SSE and local resources and HTML'}};
const path='parity/oracle/fixtures/maintenance-cli.json';
if(process.argv.includes('--check')){if(JSON.stringify(fixture)!==JSON.stringify(JSON.parse(readFileSync(path))))throw Error('fixture drift');}else writeFileSync(path,JSON.stringify(fixture,null,2)+'\n');
console.log(outcome);
