import { caseDigest, observationDigest } from './fixture-hash.mjs';
import { execFileSync } from 'node:child_process';
import { realpathSync, symlinkSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const pi = resolve(process.argv.find((v, i) => i > 1 && !v.startsWith('--')) ?? join(root, '.upstream/pi'));
const output = join(root, 'parity/oracle/fixtures/session-reload.json');
const lock = JSON.parse(readFileSync(join(root, 'parity/baseline/upstream.lock.json'), 'utf8'));
if (execFileSync('git', ['-C', pi, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim() !== lock.upstream.commit) throw Error('baseline mismatch');
if (execFileSync('git', ['-C', pi, 'status', '--porcelain', '--untracked-files=no'], { encoding: 'utf8' }).trim()) throw Error('dirty baseline');
process.env.COLORTERM = 'truecolor';
const reference = 'packages/coding-agent/src/core/sdk.ts#createAgentSession + agent-session.ts#reload';
const load = p => import(pathToFileURL(join(pi, 'packages', p)));
const { createAgentSession } = await load('coding-agent/src/core/sdk.ts');
const { DefaultResourceLoader } = await load('coding-agent/src/core/resource-loader.ts');
const { SettingsManager } = await load('coding-agent/src/core/settings-manager.ts');
const { SessionManager } = await load('coding-agent/src/core/session-manager.ts');
const { ModelRuntime } = await load('coding-agent/src/core/model-runtime.ts');
const { AuthStorage } = await load('coding-agent/src/core/auth-storage.ts');
const { createFauxCore, fauxAssistantMessage } = await load('ai/src/providers/faux.ts');
const dark = JSON.parse(readFileSync(join(pi, 'packages/coding-agent/src/modes/interactive/theme/dark.json'), 'utf8'));
const input = { versions: ['ONE', 'TWO'], calls: ['/task ARG', '/task ARG', '/skill:work ARG', '/added ARG', '/task ARG', '/skill:work ARG'] };
const dir = realpathSync(mkdtempSync(join(tmpdir(), 'pi-reload-')));
let session;
let outcomes;
try {
  process.env.HOME = join(dir, 'home');
  const cwd = join(dir, 'repo'), agentDir = join(dir, 'agent');
  const write = (p, text) => { mkdirSync(dirname(join(dir,p)), { recursive:true }); writeFileSync(join(dir,p),text); };
  const resources = version => {
    write('agent/SYSTEM.md',version);
    write('repo/AGENTS.md','CONTEXT_'+version);
    write('agent/APPEND_SYSTEM.md','APPEND_'+version);
    write('agent/prompts/task.md',version+' $1');
    write('agent/skills/work/SKILL.md',`---\nname: work\ndescription: SKILL_${version}\n---\nBODY_${version}`);
    write('agent/themes/local.json',JSON.stringify({...dark,name:'local',colors:{...dark.colors,accent:version==='ONE'?'#111111':'#222222'}}));
  };
  resources('ONE'); write('agent/settings.json',JSON.stringify({compaction:{enabled:false},retry:{enabled:false}}));
  const settings = SettingsManager.create(cwd,agentDir); settings.setProjectTrusted(false);
  const loader = new DefaultResourceLoader({cwd,agentDir,settingsManager:settings,noExtensions:true}); await loader.reload();
  const runtime = await ModelRuntime.create({credentials:AuthStorage.inMemory(),modelsPath:null,allowModelNetwork:false});
  runtime.registerProvider('deepseek',{api:'openai-completions',apiKey:'fixture',baseUrl:'https://invalid.test',models:[{id:'deepseek-v4-flash',name:'test',reasoning:true,input:['text'],cost:{input:0,output:0,cacheRead:0,cacheWrite:0},contextWindow:32000,maxTokens:2048}]});
  const manager = SessionManager.create(cwd,join(dir,'sessions'));
  ({session} = await createAgentSession({cwd,agentDir,modelRuntime:runtime,model:runtime.getModel('deepseek','deepseek-v4-flash'),sessionManager:manager,settingsManager:settings,resourceLoader:loader,tools:['read'],thinkingLevel:'high'}));
  const core = createFauxCore({}); session.agent.streamFunction=core.streamSimple;
  const requests=[],states=[];
  const prompt = s => s.replace(/\n\nPi documentation \(read only[\s\S]*?(?=\nCurrent working directory:)/, '').replace('operating inside pi,', 'operating inside pig,');
  const normalize = v => JSON.parse(JSON.stringify(v).replaceAll(dir,'$ROOT'));
  const request = async text => {core.setResponses([(c)=>{requests.push(normalize({system:prompt(c.systemPrompt),text:c.messages.at(-1).content,history:c.messages.length}));return fauxAssistantMessage('OK')}]);await session.prompt(text)};
  const capture = label => states.push(normalize({label,prompts:session.promptTemplates.map(p=>p.name),skills:loader.getSkills().skills.map(s=>s.description),themes:loader.getThemes().themes.map(t=>t.fg('accent','X')),system:prompt(session.systemPrompt),steering:session.steeringMode,followUp:session.followUpMode}));
  capture('initial'); await request(input.calls[0]);
  const before={messages:JSON.stringify(session.messages),entries:JSON.stringify(manager.getEntries()),leaf:manager.getLeafId(),file:manager.getSessionFile(),id:session.sessionId,model:JSON.stringify(session.model),thinking:session.thinkingLevel,tools:JSON.stringify(session.getActiveToolNames())};
  resources('TWO'); write('agent/prompts/added.md','ADDED $1');
  write('agent/settings.json',JSON.stringify({compaction:{enabled:false},retry:{enabled:false},steeringMode:'all',followUpMode:'all'}));
  await session.reload(); capture('updated');
  const preserved=Object.fromEntries(Object.entries(before).map(([key,value])=>[key,value===({messages:JSON.stringify(session.messages),entries:JSON.stringify(manager.getEntries()),leaf:manager.getLeafId(),file:manager.getSessionFile(),id:session.sessionId,model:JSON.stringify(session.model),thinking:session.thinkingLevel,tools:JSON.stringify(session.getActiveToolNames())})[key]]));
  await request(input.calls[1]); await request(input.calls[2]); await request(input.calls[3]);
  for(const p of ['agent/SYSTEM.md','agent/APPEND_SYSTEM.md','repo/AGENTS.md','agent/prompts/task.md','agent/skills/work/SKILL.md','agent/themes/local.json'])rmSync(join(dir,p));
  await session.reload(); capture('deleted'); await request(input.calls[4]); await request(input.calls[5]);
  const originalReload=loader.reload.bind(loader);
  write('agent/settings.json',JSON.stringify({steeringMode:'one-at-a-time',followUpMode:'one-at-a-time',compaction:{enabled:false},retry:{enabled:false}}));
  loader.reload=async()=>{throw Error('RESOURCE_FAILURE')};
  let failure='';try{await session.reload()}catch(e){failure=e.message}
  capture('failed'); loader.reload=originalReload;
  write('agent/SYSTEM.md','ACTIVE');
  let enter,release;
  const entered=new Promise(r=>enter=r),gate=new Promise(r=>release=r);
  let activeInput;
  core.setResponses([async c=>{activeInput=prompt(c.systemPrompt);enter();await gate;return fauxAssistantMessage('ACTIVE_OK')}]);
  const turn=session.prompt('active');await entered;
  let loadEnter,loadRelease;
  const loadEntered=new Promise(r=>loadEnter=r),loadGate=new Promise(r=>loadRelease=r);
  loader.reload=async()=>{loadEnter();await loadGate;await originalReload()};
  const reload=session.reload();await loadEntered;
  const during={system:prompt(session.systemPrompt),prompts:session.promptTemplates.map(p=>p.name),streaming:session.isStreaming};
  loadRelease();await reload;
  const active={during,after:prompt(session.systemPrompt),streaming:session.isStreaming,input:activeInput};
  release();await turn;loader.reload=originalReload;
  active.reply=session.getLastAssistantText();
  outcomes=normalize({states,requests,preserved,failure,active});
} finally {session?.dispose();rmSync(dir,{recursive:true,force:true})}
const c = { schema_version:'1.0.0',id:'sdk/codingagent/session-reload',catalog_id:'contract:codingagent/session-reload',surface:'go-sdk',input,observe:['outcome','side_effects'] };
const observation={outcome:outcomes,side_effects:[]};
const fixture={schema_version:'1.0.0',deterministic:true,baseline_id:lock.baseline_id,baseline_commit:lock.upstream.commit,upstream:{repository:lock.upstream.repository,commit:lock.upstream.commit,reference},case:c,observation,input_hash:caseDigest(c),observation_hash:observationDigest(observation),execution_method:'node --experimental-strip-types parity/oracle/session-reload.mjs <locked-pi-checkout>',platform:'posix',environment:{node:process.version,oracle_entry:reference}};
if(process.argv.includes('--check')){const committed=JSON.parse(readFileSync(output,'utf8'));fixture.environment.node=committed.environment.node;if(JSON.stringify(fixture)!==JSON.stringify(committed))throw Error('fixture drift');console.log(`verified ${output}`)}else{writeFileSync(output,JSON.stringify(fixture,null,2)+'\n');console.log(`wrote ${output}`)}
