import {execFileSync} from 'node:child_process';
import {readFileSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {caseDigest,observationDigest} from './fixture-hash.mjs';
const pi=resolve(process.argv[2]),lock=JSON.parse(readFileSync('parity/baseline/upstream.lock.json'));
if(execFileSync('git',['-C',pi,'rev-parse','HEAD'],{encoding:'utf8'}).trim()!==lock.upstream.commit)throw Error('baseline mismatch');
if(execFileSync('git',['-C',pi,'status','--porcelain','--untracked-files=no'],{encoding:'utf8'}).trim())throw Error('dirty baseline');
const api=await import(pathToFileURL(`${pi}/packages/coding-agent/dist/modes/interactive/theme/theme.js`));
const terminal=await import(pathToFileURL(`${pi}/packages/tui/dist/terminal-colors.js`));
const {ThemeSelectorComponent}=await import(pathToFileURL(`${pi}/packages/coding-agent/dist/modes/interactive/components/theme-selector.js`));
api.initTheme('dark',false);
const reports=['\x1b]11;rgb:ffff/ffff/ffff\x07','\x1b]11;#000000\x1b\\','\x1b]11;rgba:80/40/ff/ff\x07','\x1b]11;bad\x07','\x1b[?997;1n','\x1b[?997;2n','\x1b[?997;1n\x1b[?997;2n','x'];
const env=['','0;15','15;0','0;7','0;invalid;255'];
const keys=[['\r'],['\x1b[B','\r'],['\x1b[A','\x1b'],['\x1b[B','\x1b[A','\r']];
const selectors=keys.map(keys=>{const events=[];const s=new ThemeSelectorComponent('dark',v=>events.push('select:'+v),()=>events.push('cancel'),v=>events.push('preview:'+v));for(const k of keys)s.getSelectList().handleInput(k);return events});
const outcome={reports:reports.map(s=>({rgb:terminal.parseOsc11BackgroundColor(s)??null,scheme:terminal.parseTerminalColorSchemeReport(s)??''})),env:env.map(COLORFGBG=>api.detectTerminalBackgroundFromEnv({env:{COLORFGBG}}).theme),selectors};
const c={schema_version:'1.0.0',id:'sdk/interactive/theme-runtime',catalog_id:'contract:codingagent/interactive-themes',surface:'go-sdk',input:{reports,env,keys},observe:['outcome','side_effects']};
const observation={outcome,side_effects:[]};
const fixture={schema_version:'1.0.0',deterministic:true,baseline_id:lock.baseline_id,baseline_commit:lock.upstream.commit,upstream:{repository:lock.upstream.repository,commit:lock.upstream.commit,reference:'packages/coding-agent/src/modes/interactive/theme/theme-controller.ts'},case:c,observation,input_hash:caseDigest(c),observation_hash:observationDigest(observation),execution_method:'node parity/oracle/theme-runtime.mjs <locked-pi-checkout>',platform:'any',environment:{}};
const path='parity/oracle/fixtures/theme-runtime.json';
if(process.argv.includes('--check')){if(JSON.stringify(fixture)!==JSON.stringify(JSON.parse(readFileSync(path))))throw Error('fixture drift');}else writeFileSync(path,JSON.stringify(fixture,null,2)+'\n');
console.log(outcome);
