//go:build ignore

// Generate the Unicode 16 delta over the pinned x/text Unicode 15 tables.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"strconv"
	"strings"

	"golang.org/x/text/unicode/norm"
)

func main() {
	if len(os.Args) != 2 {
		panic("usage: go run parity/generate/edit-unicode.go <UnicodeData-16.0.0.txt>")
	}
	data, err := os.ReadFile(os.Args[1])
	if err != nil {
		panic(err)
	}
	if fmt.Sprintf("%x", sha256.Sum256(data)) != "ff58e5823bd095166564a006e47d111130813dcf8bf234ef79fa51a870edb48f" || norm.Version != "15.0.0" {
		panic("requires official UnicodeData 16.0.0 and x/text Unicode 15.0.0")
	}
	command := exec.Command("node", "--input-type=module", "-e", `
 import fs from 'node:fs';
 if(process.versions.unicode!=="16.0") throw new Error("requires Node with Unicode 16.0");
 const rows=[];
 for(const line of fs.readFileSync(0,'utf8').trim().split('\n')) {
  const f=line.split(';'), cp=parseInt(f[0],16), char=String.fromCodePoint(cp);
  if(!f[5] && f[3]==='0') continue;
  const row={cp,ccc:Number(f[3]),nfkd:char.normalize('NFKD')};
  if(f[5] && !f[5].startsWith('<')) {
   const pair=f[5].split(' ').map(x=>parseInt(x,16));
   if(pair.length===2 && String.fromCodePoint(...pair).normalize('NFC')===char) row.pair=pair;
  }
  rows.push(row);
 }
 process.stdout.write(JSON.stringify(rows));`)
	command.Stdin = bytes.NewReader(data)
	command.Stderr = os.Stderr
	output, err := command.Output()
	if err != nil {
		panic(err)
	}
	var rows []struct {
		CP   rune
		CCC  uint8
		NFKD string
		Pair []rune
	}
	if err := json.Unmarshal(output, &rows); err != nil {
		panic(err)
	}
	var source strings.Builder
	fmt.Fprintf(&source, "// Code generated by parity/generate/edit-unicode.go; DO NOT EDIT.\n// UnicodeData 16.0.0 SHA-256: %x\n// Unicode License v3: THIRD_PARTY_LICENSES/Unicode-3.0.txt\n\npackage codingagent\n\n", sha256.Sum256(data))
	source.WriteString("var editUnicode16Decomposition = map[rune]string{\n")
	for _, row := range rows {
		if norm.NFKD.String(string(row.CP)) != row.NFKD {
			fmt.Fprintf(&source, "%#x:%s,\n", row.CP, strconv.QuoteToASCII(row.NFKD))
		}
	}
	source.WriteString("}\n\nvar editUnicode16CCC = map[rune]uint8{\n")
	for _, row := range rows {
		if norm.NFKD.PropertiesString(string(row.CP)).CCC() != row.CCC {
			fmt.Fprintf(&source, "%#x:%d,\n", row.CP, row.CCC)
		}
	}
	source.WriteString("}\n\nvar editUnicode16Composition = map[[2]rune]rune{\n")
	for _, row := range rows {
		if len(row.Pair) == 2 && norm.NFC.String(string(row.Pair)) != string(row.CP) {
			fmt.Fprintf(&source, "{%#x,%#x}:%#x,\n", row.Pair[0], row.Pair[1], row.CP)
		}
	}
	source.WriteString("}\n")
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("codingagent/edit_unicode_data.go", formatted, 0644); err != nil {
		panic(err)
	}
}
