// Package surface implements the offline loader and validator for the Pi public
// surface view (issue #21): parity/surface/symbols.jsonl, the machine-readable
// authority of every exported symbol of the seven in-scope modules with its
// public members, parallel to parity/inventory/files.jsonl.
//
// The symbols.jsonl file is generated by parity/extract/surface.mjs using the
// locked TypeScript Compiler; that extraction is the ONLY step that needs Node.
// This package is stdlib-only and fully offline: it reads the committed snapshot
// and the Parity Catalog and performs no network access or subprocess execution.
// Like internal/baseline and internal/inventory, it MUST NOT be imported by
// cmd/pig or cmd/pig-ai, whose binaries are asserted to carry no net/os/exec
// dependencies.
package surface

import (
	"bufio"
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"sort"
	"strings"
)

// SchemaVersion is the surface snapshot schema version. It matches the value
// emitted by parity/extract/surface.mjs.
const SchemaVersion = "1.1.0"

// Repository is the fixed upstream repository every symbol is extracted from.
const Repository = "https://github.com/badlogic/pi-mono"

// Module describes one in-scope Pi module for surface validation: its upstream
// package directory, the Pig module bucket, and the module-level Parity Catalog
// entry that must own its symbols. The set mirrors internal/inventory.Modules
// and the MODULES table in parity/extract/surface.mjs.
type Module struct {
	// UpstreamDir is the package directory relative to the Pi checkout root,
	// e.g. "packages/coding-agent". It is also the prefix of every symbol
	// reference in the module.
	UpstreamDir string
	// PigModule is the Pig module bucket, e.g. "ai" or "codingagent".
	PigModule string
	// CatalogID is the module-level catalog entry that owns the module's symbols.
	CatalogID string
}

// UpstreamName is the upstream module name (the package directory without the
// "packages/" prefix, e.g. "coding-agent"). It is the value stored in each
// symbol's upstream.module.
func (m Module) UpstreamName() string { return strings.TrimPrefix(m.UpstreamDir, "packages/") }

// Modules is the fixed, ordered set of seven in-scope Pi modules, ordered by
// Pig module name so generated output is stable.
var Modules = []Module{
	{UpstreamDir: "packages/agent", PigModule: "agent", CatalogID: "module-agent"},
	{UpstreamDir: "packages/ai", PigModule: "ai", CatalogID: "module-ai"},
	{UpstreamDir: "packages/client", PigModule: "client", CatalogID: "module-client"},
	{UpstreamDir: "packages/coding-agent", PigModule: "codingagent", CatalogID: "module-codingagent"},
	{UpstreamDir: "packages/protocol", PigModule: "protocol", CatalogID: "module-protocol"},
	{UpstreamDir: "packages/telemetry", PigModule: "telemetry", CatalogID: "module-telemetry"},
	{UpstreamDir: "packages/tui", PigModule: "tui", CatalogID: "module-tui"},
}

// moduleByPig indexes Modules by Pig module name.
var moduleByPig = func() map[string]Module {
	m := make(map[string]Module, len(Modules))
	for _, mod := range Modules {
		m[mod.PigModule] = mod
	}
	return m
}()

// kindEnum is the set of symbol kinds parity/extract/surface.mjs can emit
// (see symbolKind there). It is the enum enforced by Validate.
var kindEnum = map[string]bool{
	"class":     true,
	"interface": true,
	"type":      true,
	"enum":      true,
	"function":  true,
	"method":    true,
	"namespace": true,
	"const":     true,
	"value":     true,
}

// Upstream records the fixed Pi baseline provenance for a symbol. Its shape
// mirrors catalog.Upstream but is kept local so this package stays independent.
type Upstream struct {
	Module     string `json:"module"`
	Repository string `json:"repository"`
	Commit     string `json:"commit"`
	Reference  string `json:"reference"`
}

// Symbol is a single exported public symbol of an in-scope module. The canonical
// symbols.jsonl holds exactly one such object per line, sorted by id.
type Symbol struct {
	SchemaVersion  string   `json:"schema_version"`
	ID             string   `json:"id"`
	Module         string   `json:"module"`
	Name           string   `json:"name"`
	Kind           string   `json:"kind"`
	Constructible  bool     `json:"constructible"`
	Upstream       Upstream `json:"upstream"`
	ExportSubpaths []string `json:"export_subpaths"`
	Members        []string `json:"members"`
	StaticMembers  []string `json:"static_members"`
}

// Manifest is the versioned surface manifest (parity/surface/manifest.json). It
// anchors the baseline commit and carries coverage counts, mirroring the
// inventory manifest.
type Manifest struct {
	SchemaVersion     string         `json:"schema_version"`
	BaselineCommit    string         `json:"baseline_commit"`
	Symbols           string         `json:"symbols"`
	SymbolCount       int            `json:"symbol_count"`
	MemberCount       int            `json:"member_count"`
	StaticMemberCount int            `json:"static_member_count"`
	ConstructorCount  int            `json:"constructor_count"`
	ModuleCounts      map[string]int `json:"module_counts"`
	KindCounts        map[string]int `json:"kind_counts"`
}

// Kind identifies a consistency failure category.
type Kind string

// Consistency failure kinds.
const (
	KindDuplicateID      Kind = "duplicate_id"
	KindMissingField     Kind = "missing_field"
	KindIllegalKind      Kind = "illegal_kind"
	KindUnknownModule    Kind = "unknown_module"
	KindMalformedID      Kind = "malformed_id"
	KindProvenance       Kind = "provenance_mismatch"
	KindCommitMismatch   Kind = "commit_mismatch"
	KindUnmapped         Kind = "unmapped"
	KindModuleUncovered  Kind = "module_uncovered"
	KindNotSorted        Kind = "not_sorted"
	KindManifestMismatch Kind = "manifest_mismatch"
	KindSchemaVersion    Kind = "schema_version"
)

// Sentinel errors, matchable with errors.Is.
var (
	ErrDuplicateID      = errors.New("surface: duplicate symbol id")
	ErrMissingField     = errors.New("surface: symbol missing required field")
	ErrIllegalKind      = errors.New("surface: illegal symbol kind")
	ErrUnknownModule    = errors.New("surface: unknown module")
	ErrMalformedID      = errors.New("surface: symbol id does not match module/name")
	ErrProvenance       = errors.New("surface: upstream provenance does not match module")
	ErrCommitMismatch   = errors.New("surface: upstream commit does not match manifest baseline")
	ErrUnmapped         = errors.New("surface: module has no resolvable owning catalog entry")
	ErrModuleUncovered  = errors.New("surface: in-scope module has no extracted symbols")
	ErrNotSorted        = errors.New("surface: members, static_members, or export_subpaths not sorted and unique")
	ErrManifestMismatch = errors.New("surface: manifest counts do not match symbols")
	ErrSchemaVersion    = errors.New("surface: schema version missing or inconsistent")
	ErrMalformedLine    = errors.New("surface: malformed symbols.jsonl line")
)

func sentinelFor(k Kind) error {
	switch k {
	case KindDuplicateID:
		return ErrDuplicateID
	case KindMissingField:
		return ErrMissingField
	case KindIllegalKind:
		return ErrIllegalKind
	case KindUnknownModule:
		return ErrUnknownModule
	case KindMalformedID:
		return ErrMalformedID
	case KindProvenance:
		return ErrProvenance
	case KindCommitMismatch:
		return ErrCommitMismatch
	case KindUnmapped:
		return ErrUnmapped
	case KindModuleUncovered:
		return ErrModuleUncovered
	case KindNotSorted:
		return ErrNotSorted
	case KindManifestMismatch:
		return ErrManifestMismatch
	case KindSchemaVersion:
		return ErrSchemaVersion
	default:
		return nil
	}
}

// Error is the typed consistency error. It carries a Kind (for errors.As) and
// unwraps to its Kind sentinel (for errors.Is).
type Error struct {
	Kind    Kind
	ID      string
	Message string
}

func (e *Error) Error() string {
	msg := string(e.Kind)
	if e.ID != "" {
		msg += " (" + e.ID + ")"
	}
	if e.Message != "" {
		msg += ": " + e.Message
	}
	return msg
}

// Unwrap returns the Kind sentinel so errors.Is matches it.
func (e *Error) Unwrap() error { return sentinelFor(e.Kind) }

func newError(kind Kind, id, format string, args ...any) *Error {
	return &Error{Kind: kind, ID: id, Message: fmt.Sprintf(format, args...)}
}

// ParseError identifies a malformed line while loading symbols.jsonl.
type ParseError struct {
	Line int
	err  error
}

func (e *ParseError) Error() string {
	return fmt.Sprintf("%s: line %d: %v", ErrMalformedLine.Error(), e.Line, e.err)
}

// Unwrap returns ErrMalformedLine so callers can match it with errors.Is.
func (e *ParseError) Unwrap() error { return ErrMalformedLine }

// LoadSymbols parses a symbols.jsonl surface view line by line. A malformed line
// or a record missing the required constructible field is an error identifying
// the line number.
func LoadSymbols(path string) ([]Symbol, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var symbols []Symbol
	scanner := bufio.NewScanner(bytes.NewReader(data))
	scanner.Buffer(make([]byte, 0, 64*1024), 4*1024*1024)
	line := 0
	for scanner.Scan() {
		line++
		raw := scanner.Bytes()
		if len(bytes.TrimSpace(raw)) == 0 {
			return nil, &ParseError{Line: line, err: errors.New("blank line not allowed")}
		}
		var required struct {
			Constructible *bool `json:"constructible"`
		}
		if err := json.Unmarshal(raw, &required); err != nil {
			return nil, &ParseError{Line: line, err: err}
		}
		if required.Constructible == nil {
			return nil, &ParseError{Line: line, err: errors.New("required field constructible is missing or null")}
		}
		dec := json.NewDecoder(bytes.NewReader(raw))
		dec.DisallowUnknownFields()
		var sym Symbol
		if err := dec.Decode(&sym); err != nil {
			return nil, &ParseError{Line: line, err: err}
		}
		if dec.More() {
			return nil, &ParseError{Line: line, err: errors.New("more than one JSON value on line")}
		}
		symbols = append(symbols, sym)
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	return symbols, nil
}

// EncodeSymbols serialises symbols as canonical JSONL: one compact object per
// line, sorted by id, with HTML escaping disabled so ids and references (which
// contain <, >, & in generics like Promise<T> or Map<K,V>) stay byte-clean and
// the diff stays minimal.
func EncodeSymbols(symbols []Symbol) ([]byte, error) {
	sorted := append([]Symbol(nil), symbols...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].ID < sorted[j].ID })
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	for _, sym := range sorted {
		if err := enc.Encode(sym); err != nil {
			return nil, err
		}
	}
	return buf.Bytes(), nil
}

// LoadManifest reads and decodes the surface manifest JSON.
func LoadManifest(path string) (Manifest, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return Manifest{}, err
	}
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	var m Manifest
	if err := dec.Decode(&m); err != nil {
		return Manifest{}, err
	}
	return m, nil
}

// BuildManifest derives the manifest counts from symbols.
func BuildManifest(symbols []Symbol, baselineCommit string) Manifest {
	moduleCounts := map[string]int{}
	kindCounts := map[string]int{}
	members := 0
	staticMembers := 0
	constructors := 0
	for _, s := range symbols {
		moduleCounts[s.Module]++
		kindCounts[s.Kind]++
		members += len(s.Members)
		staticMembers += len(s.StaticMembers)
		if s.Constructible {
			constructors++
		}
	}
	return Manifest{
		SchemaVersion:     SchemaVersion,
		BaselineCommit:    baselineCommit,
		Symbols:           "symbols.jsonl",
		SymbolCount:       len(symbols),
		MemberCount:       members,
		StaticMemberCount: staticMembers,
		ConstructorCount:  constructors,
		ModuleCounts:      moduleCounts,
		KindCounts:        kindCounts,
	}
}

// EncodeManifest serialises the manifest as pretty JSON with a trailing newline.
func EncodeManifest(m Manifest) ([]byte, error) {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(m); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// isSortedUnique reports whether values are strictly increasing (sorted and
// free of duplicates).
func isSortedUnique(values []string) bool {
	for i := 1; i < len(values); i++ {
		if values[i-1] >= values[i] {
			return false
		}
	}
	return true
}

// Validate enforces the offline surface rules against a loaded snapshot. It
// requires the set of known Parity Catalog entry ids so it can reject symbols
// whose owning module-level catalog entry does not resolve (unmapped surface).
//
// It rejects: symbols missing a required field; duplicate ids; illegal kind or a
// non-class marked constructible; unknown module; ids that disagree with
// module/name; upstream provenance that does not match the module (repository,
// module name, reference prefix); upstream commit that differs from the manifest
// baseline; a module whose module-level catalog entry is absent from the catalog;
// in-scope modules with no symbols; members, static_members, or export_subpaths
// that are not sorted-and-unique; and manifests whose symbol, member,
// static-member, or constructor counts disagree with the symbols.
func Validate(symbols []Symbol, manifest Manifest, catalogIDs map[string]bool) error {
	if manifest.SchemaVersion == "" {
		return newError(KindMissingField, "", "manifest schema_version is empty")
	}
	if manifest.SchemaVersion != SchemaVersion {
		return newError(KindSchemaVersion, "", "manifest schema_version=%q want=%q", manifest.SchemaVersion, SchemaVersion)
	}
	if manifest.BaselineCommit == "" {
		return newError(KindMissingField, "", "manifest baseline_commit is empty")
	}

	seen := make(map[string]bool, len(symbols))
	moduleCounts := map[string]int{}
	kindCounts := map[string]int{}
	members := 0
	staticMembers := 0
	constructors := 0

	for _, s := range symbols {
		switch {
		case s.SchemaVersion == "":
			return newError(KindMissingField, s.ID, "schema_version is empty")
		case s.SchemaVersion != SchemaVersion:
			return newError(KindSchemaVersion, s.ID, "schema_version=%q want=%q", s.SchemaVersion, SchemaVersion)
		case s.ID == "":
			return newError(KindMissingField, s.ID, "id is empty")
		case s.Module == "":
			return newError(KindMissingField, s.ID, "module is empty")
		case s.Name == "":
			return newError(KindMissingField, s.ID, "name is empty")
		case s.Kind == "":
			return newError(KindMissingField, s.ID, "kind is empty")
		case s.Upstream.Repository == "":
			return newError(KindMissingField, s.ID, "upstream.repository is empty")
		case s.Upstream.Commit == "":
			return newError(KindMissingField, s.ID, "upstream.commit is empty")
		case s.Upstream.Reference == "":
			return newError(KindMissingField, s.ID, "upstream.reference is empty")
		case s.Upstream.Module == "":
			return newError(KindMissingField, s.ID, "upstream.module is empty")
		}

		if seen[s.ID] {
			return newError(KindDuplicateID, s.ID, "")
		}
		seen[s.ID] = true

		if !kindEnum[s.Kind] {
			return newError(KindIllegalKind, s.ID, "%s", s.Kind)
		}
		if s.Constructible && s.Kind != "class" {
			return newError(KindIllegalKind, s.ID, "constructible=true requires kind=class, got %q", s.Kind)
		}

		mod, ok := moduleByPig[s.Module]
		if !ok {
			return newError(KindUnknownModule, s.ID, "%s", s.Module)
		}

		// The id encodes module and name: symbol:<module>/<relpath>#<name>.
		body, hadPrefix := strings.CutPrefix(s.ID, "symbol:")
		left, name, hadHash := strings.Cut(body, "#")
		relpath, hadSlash := strings.CutPrefix(left, s.Module+"/")
		switch {
		case !hadPrefix || !hadHash || !hadSlash:
			return newError(KindMalformedID, s.ID, "id is not symbol:<module>/<relpath>#<name>")
		case name != s.Name:
			return newError(KindMalformedID, s.ID, "id name %q != name %q", name, s.Name)
		case relpath == "":
			return newError(KindMalformedID, s.ID, "id has empty relpath")
		}

		// Provenance must match the module: fixed repository, upstream module
		// name (coding-agent, not codingagent), and a reference that is the
		// module dir joined with the id's relpath and name.
		wantRef := mod.UpstreamDir + "/" + relpath + "#" + name
		switch {
		case s.Upstream.Repository != Repository:
			return newError(KindProvenance, s.ID, "upstream.repository %q != %q", s.Upstream.Repository, Repository)
		case s.Upstream.Module != mod.UpstreamName():
			return newError(KindProvenance, s.ID, "upstream.module %q != %q", s.Upstream.Module, mod.UpstreamName())
		case s.Upstream.Reference != wantRef:
			return newError(KindProvenance, s.ID, "upstream.reference %q != %q", s.Upstream.Reference, wantRef)
		}

		if s.Upstream.Commit != manifest.BaselineCommit {
			return newError(KindCommitMismatch, s.ID, "%s", s.Upstream.Commit)
		}

		// Every symbol must map to an existing module-level catalog entry.
		if !catalogIDs[mod.CatalogID] {
			return newError(KindUnmapped, s.ID, "owning catalog entry %s is not present", mod.CatalogID)
		}

		// The generated authority must be deterministic: instance/type members,
		// static members, and export subpaths are sorted and unique, with no
		// empty names. static_members must be present even when empty so the
		// schema distinguishes an extracted empty set from an omitted field.
		for _, name := range s.Members {
			if name == "" {
				return newError(KindMissingField, s.ID, "member name is empty")
			}
		}
		if !isSortedUnique(s.Members) {
			return newError(KindNotSorted, s.ID, "members not sorted and unique")
		}
		if s.StaticMembers == nil {
			return newError(KindMissingField, s.ID, "static_members is missing")
		}
		for _, name := range s.StaticMembers {
			if name == "" {
				return newError(KindMissingField, s.ID, "static member name is empty")
			}
		}
		if !isSortedUnique(s.StaticMembers) {
			return newError(KindNotSorted, s.ID, "static_members not sorted and unique")
		}
		if len(s.ExportSubpaths) == 0 {
			return newError(KindMissingField, s.ID, "export_subpaths is empty")
		}
		for _, sp := range s.ExportSubpaths {
			if sp == "" {
				return newError(KindMissingField, s.ID, "export subpath is empty")
			}
		}
		if !isSortedUnique(s.ExportSubpaths) {
			return newError(KindNotSorted, s.ID, "export_subpaths not sorted and unique")
		}

		moduleCounts[s.Module]++
		kindCounts[s.Kind]++
		members += len(s.Members)
		staticMembers += len(s.StaticMembers)
		if s.Constructible {
			constructors++
		}
	}

	for _, m := range Modules {
		if moduleCounts[m.PigModule] == 0 {
			return newError(KindModuleUncovered, "", "module %s has no extracted symbols", m.PigModule)
		}
	}

	if manifest.SymbolCount != len(symbols) {
		return newError(KindManifestMismatch, "", "symbol_count=%d actual=%d", manifest.SymbolCount, len(symbols))
	}
	if manifest.MemberCount != members {
		return newError(KindManifestMismatch, "", "member_count=%d actual=%d", manifest.MemberCount, members)
	}
	if manifest.StaticMemberCount != staticMembers {
		return newError(KindManifestMismatch, "", "static_member_count=%d actual=%d", manifest.StaticMemberCount, staticMembers)
	}
	if manifest.ConstructorCount != constructors {
		return newError(KindManifestMismatch, "", "constructor_count=%d actual=%d", manifest.ConstructorCount, constructors)
	}
	if err := compareCounts("module_counts", manifest.ModuleCounts, moduleCounts); err != nil {
		return err
	}
	if err := compareCounts("kind_counts", manifest.KindCounts, kindCounts); err != nil {
		return err
	}
	return nil
}

// compareCounts checks that a manifest count map equals the actual counts,
// ignoring keys that are explicitly zero on both sides.
func compareCounts(label string, manifestCounts, actual map[string]int) error {
	keys := make(map[string]bool)
	for k := range manifestCounts {
		keys[k] = true
	}
	for k := range actual {
		keys[k] = true
	}
	for k := range keys {
		if manifestCounts[k] != actual[k] {
			return newError(KindManifestMismatch, "", "%s[%s]=%d actual=%d", label, k, manifestCounts[k], actual[k])
		}
	}
	return nil
}
